var annotated_dup =
[
    [ "ApplicationLogger", "class_application_logger.html", null ],
    [ "AutoIndexState", "class_auto_index_state.html", "class_auto_index_state" ],
    [ "BaseCounter", "class_base_counter.html", "class_base_counter" ],
    [ "CgiExecutionState", "class_cgi_execution_state.html", "class_cgi_execution_state" ],
    [ "ContentExtractionState", "class_content_extraction_state.html", "class_content_extraction_state" ],
    [ "DeleteMethodState", "class_delete_method_state.html", "class_delete_method_state" ],
    [ "ErrorCounter", "class_error_counter.html", null ],
    [ "FilePathGenerationState", "class_file_path_generation_state.html", "class_file_path_generation_state" ],
    [ "HeaderParserStream", "class_header_parser_stream.html", "class_header_parser_stream" ],
    [ "HttpCgi", "struct_http_cgi.html", null ],
    [ "HttpRequest", "struct_http_request.html", null ],
    [ "HttpResponse", "struct_http_response.html", null ],
    [ "HttpTransaction", "class_http_transaction.html", "class_http_transaction" ],
    [ "HttpWorkflowManager", "class_http_workflow_manager.html", "class_http_workflow_manager" ],
    [ "ICounter", "class_i_counter.html", null ],
    [ "IdentifyLocationState", "class_identify_location_state.html", "class_identify_location_state" ],
    [ "IHttpProcessingStep", "class_i_http_processing_step.html", null ],
    [ "IHttpWorkflowManager", "class_i_http_workflow_manager.html", null ],
    [ "LocationDirective", "class_location_directive.html", null ],
    [ "MimeType", "class_mime_type.html", null ],
    [ "NetworkService", "class_network_service.html", "class_network_service" ],
    [ "ParsingBodyState", "class_parsing_body_state.html", "class_parsing_body_state" ],
    [ "PortMapping", "class_port_mapping.html", "class_port_mapping" ],
    [ "RateLimiter", "class_rate_limiter.html", null ],
    [ "ResponseStrBuildState", "class_response_str_build_state.html", "class_response_str_build_state" ],
    [ "ServerDirective", "class_server_directive.html", null ],
    [ "ServerLoopController", "class_server_loop_controller.html", null ],
    [ "ServerManeger", "class_server_maneger.html", "class_server_maneger" ],
    [ "SignalHandler", "class_signal_handler.html", null ],
    [ "SocketState", "class_socket_state.html", "class_socket_state" ],
    [ "Tokenize", "class_tokenize.html", "class_tokenize" ],
    [ "UtilHttpProcessingStep", "class_util_http_processing_step.html", null ],
    [ "VectorStreamBuf", "class_vector_stream_buf.html", "class_vector_stream_buf" ]
];